### ISSUE TITLE
can't git clone

### ISSUE THREAD

**Issue by faizH3** [faizH3/newbie#6]
![Screenshot (48)](https://user-images.githubusercontent.com/59959639/103161221-0fb38800-4811-11eb-990c-1e38dd7e12b3.png)
how to git clone? please help me!

**Comment by ekovegeance** [comment]
`git`clone https://github.com/ekovegeance/ComputerScience.git

**Comment by ekovegeance** [comment]
[DOCUMENTATION](https://docs.ekovegeance.xyz)
